const SUCCESSFUL = 'SUCCESSFUL';
const NOT_FOUND = 'NOT_FOUND';
const CREATED = 'CREATED';
const BAD_REQUEST = 'BAD_REQUEST';

module.exports = {
  SUCCESSFUL,
  NOT_FOUND,
  CREATED,
  BAD_REQUEST,
};
